# x987 Ruff config — velocity mode
line-length = 120
target-version = "py313"

[lint]
# Keep correctness (pycodestyle errors) + pyflakes only.
select = ["E", "F"]

# TEMP: ignore style codes that trigger repo-wide churn.
# Remove these gradually per-module as we touch files.
ignore = ["E501","E401","E701","E702","E703","E722"]

exclude = ["x987-data","**/__pycache__"]

[format]
line-ending = "lf"
indent-style = "space"
quote-style = "preserve"
